var ImageData = [
      { src: "./media/oi/elaina (1).jpg", width: 0, height: 0, id: 0 },
      { src: "./media/oi/elaina (1).png", width: 0, height: 0, id: 0 },
      { src: "./media/oi/elaina (2).jpg", width: 0, height: 0, id: 0 },
      { src: "./media/oi/elaina (2).png", width: 0, height: 0, id: 0 },
      { src: "./media/oi/elaina (3).jpg", width: 0, height: 0, id: 0 },
      { src: "./media/oi/elaina (3).png", width: 0, height: 0, id: 0 },
      { src: "./media/oi/elaina (4).jpg", width: 0, height: 0, id: 0 },
      { src: "./media/oi/elaina (5).jpg", width: 0, height: 0, id: 0 },
      { src: "./media/oi/elaina (6).jpg", width: 0, height: 0, id: 0 },
      { src: "./media/old/Elaina/Elaina.png", width: 0, height: 0, id: 0 },
      { src: "./media/old/Elaina/Elaina1.jpeg", width: 0, height: 0, id: 0 },
      { src: "./media/old/Elaina/Elaina2.jpg", width: 0, height: 0, id: 0 },
      { src: "./media/old/Elaina/Elaina3.png", width: 0, height: 0, id: 0 },
      { src: "./media/old/Elaina/Elaina4.jpeg", width: 0, height: 0, id: 0 },
      { src: "./media/old/Elaina/Elaina5.jpg", width: 0, height: 0, id: 0 },
      { src: "./media/old/Elaina/Elaina6.png", width: 0, height: 0, id: 0 },
      { src: "./media/old/Elaina/Elaina7.jpeg", width: 0, height: 0, id: 0 },
      { src: "./media/old/Elaina/Elaina8.jpg", width: 0, height: 0, id: 0 },
      { src: "./media/old/Elaina/Elaina9.png", width: 0, height: 0, id: 0 },
      { src: "./media/old/Elaina/Elaina10.jpeg", width: 0, height: 0, id: 0 },
      { src: "./media/old/Elaina/Elaina11.jpg", width: 0, height: 0, id: 0 },
      { src: "./media/old/Elaina/Elaina12.png", width: 0, height: 0, id: 0 },
      { src: "./media/old/Elaina/Elaina13.jpeg", width: 0, height: 0, id: 0 },
      { src: "./media/old/Elaina/Elaina14.jpg", width: 0, height: 0, id: 0 },
      { src: "./media/old/Elaina/Elaina15.png", width: 0, height: 0, id: 0 },
      { src: "./media/old/Elaina/Elaina16.jpeg", width: 0, height: 0, id: 0 },
      { src: "./media/old/Elaina/Elaina17.jpg", width: 0, height: 0, id: 0 },
      { src: "./media/old/Elaina/Elaina18.png", width: 0, height: 0, id: 0 },
      { src: "./media/old/Elaina/Elaina19.jpeg", width: 0, height: 0, id: 0 },
      { src: "./media/old/Elaina/Elaina21.jpeg", width: 0, height: 0, id: 0 },
    ];
